name: medusa_admin
version: 1.0.3
publish_to: none
description: A medusa store manger for mobile !.
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  # State management packages
  # -------------------
  flutter_bloc: ^9.1.1
  # -------------------
  # Dependency injection packages
  # -------------------
  get_it: ^8.0.3
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  # -------------------

  # App routing
  # -------------------
  auto_route: ^10.1.0
  # -------------------

  # Image picker packages
  #--------------------
  image_picker: ^1.0.2
  image_cropper: ^9.1.0
  uuid: ^4.2.1
  #--------------------

  # UI & animation packages
  # -------------------
  adaptive_dialog: ^2.0.0
  flutter_settings_ui: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.6
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.20.2
  pull_to_refresh: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  flex_color_scheme: ^8.2.0
  loading_animation_widget: ^1.2.0+4
  flutter_speed_dial: ^7.0.0
  flutter_slidable: ^4.0.0
  flutter_animate: ^4.1.1+1
  super_banners: ^0.0.1
  google_fonts: ^6.1.0
  skeletonizer: ^2.0.1
  fluttertoast: ^8.2.4
  info_popup: ^4.3.1
  #--------------------



  # Storage packages
  # -------------------
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3
  # -------------------

  # Firebase packages
  # -------------------
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  # -------------------

  # Network packages
  # -------------------
  dio: ^5.4.0
  internet_connection_checker_plus: ^2.1.0
  # -------------------


  # Miscellaneous packages
  # -------------------
  equatable: ^2.0.5
  flag: ^7.0.0
  timeago: ^3.5.0
  gap: ^3.0.1
  multiple_result: ^5.0.0
  package_info_plus: ^8.3.0
  multi_dropdown: ^3.0.1
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flex_expansion_tile:
    git:
      url: https://github.com/mllrr96/flex_expansion_tile.git
      ref: main

  medusa_admin_dart_client:
    git:
      url: https://github.com/mllrr96/medusa_admin_dart_client.git
      ref: main

  medusa_api_client:
    path: packages/medusa_api_client

  share_plus: ^11.0.0
  file_picker: ^10.1.9
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_octicons: ^1.51.0
  url_launcher: ^6.2.3
  simple_icons: ^14.6.1
  apk_installer: ^0.0.4
  sliver_tools: ^0.2.12
  flutter_markdown: ^0.7.7+1
  pretty_dio_logger: ^1.3.1



dev_dependencies:
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.1.0
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.3
  injectable_generator: ^2.4.1
  freezed: ^2.5.8
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - assets/images/
    - assets/product-import-template.csv
  uses-material-design: true
  fonts:
    - family: MedusaIcons
      fonts:
        - asset: fonts/MedusaIcons.ttf
flutter_launcher_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/images/medusa.png"