/// Flutter icons MedusaIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MedusaIcons
///      fonts:
///       - asset: fonts/MedusaIcons.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class MedusaIcons {
  MedusaIcons._();

  static const _kFontFam = 'MedusaIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_down_tray = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_tray = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bars_three = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_alert = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buildings = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_six_tooth = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData currency_dollar = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifying_glass_mini = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifying_glass = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_square_solid = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_mini = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt_percent = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swatch = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
