import 'package:medusa_admin_flutter/medusa_admin.dart';

extension CopyWithLineItem on LineItem {
  LineItem copyWith({
    int? quantity,
    String? title,
    String? variantId,
    String? cartId,
    String? orderId,
    String? orderEditId,
    String? originalItemId,
    int? originalTotal,
    int? originalTaxTotal,
    Cart? cart,
    Order? order,
    OrderEdit? orderEdit,
    List<LineItemAdjustment>? adjustments,
    bool? allowDiscounts,
    String? claimOrderId,
    ClaimOrder? claimOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
    int? discountTotal,
    int? fulfilledQuantity,
    int? giftCardTotal,
    bool? hasShipping,
    bool? includesTax,
    bool? isGiftCard,
    bool? isReturn,
    Map<String, dynamic>? metadata,
    int? rawDiscountTotal,
    int? shippedQuantity,
    bool? shouldMerge,
    int? subtotal,
    Swap? swap,
    String? swapId,
    List<LineItemTaxLine>? taxLines,
    int? taxTotal,
    String? thumbnail,
    String? description,
    int? unitPrice,
    int? refundable,
    int? returnedQuantity,
    int? total,
    ProductVariant? variant,
  }) {
    return LineItem(
      id: id,
      cart: cart ?? this.cart,
      claimOrder: claimOrder ?? this.claimOrder,
      claimOrderId: claimOrderId ?? this.claimOrderId,
      cartId: cartId ?? this.cartId,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      orderId: orderId ?? this.orderId,
      description: description ?? this.description,
      discountTotal: discountTotal ?? this.discountTotal,
      order: order ?? this.order,
      fulfilledQuantity: fulfilledQuantity ?? this.fulfilledQuantity,
      giftCardTotal: giftCardTotal ?? this.giftCardTotal,
      orderEdit: orderEdit ?? this.orderEdit,
      hasShipping: hasShipping ?? this.hasShipping,
      originalItemId: originalItemId ?? this.originalItemId,
      orderEditId: orderEditId ?? this.orderEditId,
      includesTax: includesTax ?? this.includesTax,
      originalTaxTotal: originalTaxTotal ?? this.originalTaxTotal,
      isGiftCard: isGiftCard ?? this.isGiftCard,
      quantity: quantity ?? this.quantity,
      isReturn: isReturn ?? this.isReturn,
      originalTotal: originalTotal ?? this.originalTotal,
      adjustments: adjustments ?? this.adjustments,
      metadata: metadata ?? this.metadata,
      allowDiscounts: allowDiscounts ?? this.allowDiscounts,
      rawDiscountTotal: rawDiscountTotal ?? this.rawDiscountTotal,
      shippedQuantity: shippedQuantity ?? this.shippedQuantity,
      shouldMerge: shouldMerge ?? this.shouldMerge,
      swap: swap ?? this.swap,
      subtotal: subtotal ?? this.subtotal,
      swapId: swapId ?? this.swapId,
      taxLines: taxLines ?? this.taxLines,
      taxTotal: taxTotal ?? this.taxTotal,
      thumbnail: thumbnail ?? this.thumbnail,
      title: title ?? this.title,
      variantId: variantId ?? this.variantId,
      variant: variant ?? this.variant,
      refundable: refundable ?? this.refundable,
      returnedQuantity: returnedQuantity ?? this.returnedQuantity,
      total: total ?? this.total,
      unitPrice: unitPrice ?? this.unitPrice,
    );
  }
}
