import 'package:medusa_admin/core/extension/money_amount_extension.dart';
import 'package:medusa_admin/core/extension/product_option_value_extension.dart';
import 'package:medusa_admin_flutter/medusa_admin.dart';

extension CopyWithProductVariant on ProductVariant {
  ProductVariant copyWith({
    String? id,
    String? title,
    String? productId,
    List<ProductOptionValue>? options,
    List<MoneyAmount>? prices,
    String? sku,
    double? weight,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? allowBackorder,
    String? barcode,
    DateTime? deletedAt,
    Product? product,
    bool? purchasable,
    String? ean,
    double? width,
    double? height,
    String? material,
    bool? manageInventory,
    Map<String, dynamic>? metadata,
    String? midCode,
    List<InventoryItem>? inventoryItems,
    int? inventoryQuantity,
    String? originCountry,
    String? hsCode,
    double? length,
    int? variantRank,
    String? upc,
  }) {
    return ProductVariant(
      id: id ?? this.id,
      title: title ?? this.title,
      productId: productId ?? this.productId,
      product: product ?? this.product,
      purchasable: purchasable ?? this.purchasable,
      ean: ean ?? this.ean,
      width: width ?? this.width,
      originCountry: originCountry ?? this.originCountry,
      hsCode: hsCode ?? this.hsCode,
      height: height ?? this.height,
      length: length ?? this.length,
      variantRank: variantRank ?? this.variantRank,
      options: options ?? this.options,
      material: material ?? this.material,
      upc: upc ?? this.upc,
      manageInventory: manageInventory ?? this.manageInventory,
      metadata: metadata ?? this.metadata,
      midCode: midCode ?? this.midCode,
      prices: prices ?? this.prices,
      inventoryItems: inventoryItems ?? this.inventoryItems,
      inventoryQuantity: inventoryQuantity ?? this.inventoryQuantity,
      sku: sku ?? this.sku,
      weight: weight ?? this.weight,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      allowBackorder: allowBackorder ?? this.allowBackorder,
      barcode: barcode ?? this.barcode,
      deletedAt: deletedAt ?? this.deletedAt,
    );
  }

  ProductVariant forUpdate({
    String? id,
    String? title,
    List<ProductOptionValue>? options,
    List<MoneyAmount>? prices,
    String? sku,
    double? weight,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? allowBackorder,
    String? barcode,
    DateTime? deletedAt,
    Product? product,
    bool? purchasable,
    String? ean,
    double? width,
    double? height,
    String? material,
    bool? manageInventory,
    Map<String, dynamic>? metadata,
    String? midCode,
    List<InventoryItem>? inventoryItems,
    int? inventoryQuantity,
    String? originCountry,
    String? hsCode,
    double? length,
    int? variantRank,
    String? upc,
  }) {
    return ProductVariant(
      id: id ?? this.id,
      title: title ?? this.title,
      sku: sku ?? this.sku,
      ean: ean ?? this.ean,
      upc: upc ?? this.upc,
      barcode: barcode ?? this.barcode,
      hsCode: hsCode ?? this.hsCode,
      inventoryQuantity: inventoryQuantity ?? this.inventoryQuantity,
      allowBackorder: allowBackorder ?? this.allowBackorder,
      manageInventory: manageInventory ?? this.manageInventory,
      height: height ?? this.height,
      length: length ?? this.length,
      width: width ?? this.width,
      weight: weight ?? this.weight,
      originCountry: originCountry ?? this.originCountry,
      midCode: midCode ?? this.midCode,
      material: material ?? this.material,
      metadata: metadata ?? this.metadata,
      options: options?.map((e) => e.forUpdate()).toList(),
      prices: prices?.map((e) => e.forUpdate()).toList(),
      //
      productId: null,
      product: null,
      purchasable: null,
      variantRank: null,
      inventoryItems: null,
      createdAt: null,
      updatedAt: null,
      deletedAt: null,
    );
  }

  ProductVariant duplicate({
    String? title,
    String? sku,
    double? weight,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? allowBackorder,
    String? barcode,
    DateTime? deletedAt,
    Product? product,
    bool? purchasable,
    String? ean,
    double? width,
    double? height,
    String? material,
    bool? manageInventory,
    Map<String, dynamic>? metadata,
    String? midCode,
    List<InventoryItem>? inventoryItems,
    int? inventoryQuantity,
    String? originCountry,
    String? hsCode,
    double? length,
    int? variantRank,
    String? upc,
  }) {
    return ProductVariant(
      id: null,
      title: title ?? this.title,
      sku: sku ?? this.sku,
      ean: ean ?? this.ean,
      upc: upc ?? this.upc,
      barcode: barcode ?? this.barcode,
      hsCode: hsCode ?? this.hsCode,
      inventoryQuantity: inventoryQuantity ?? this.inventoryQuantity,
      allowBackorder: allowBackorder ?? this.allowBackorder,
      manageInventory: manageInventory ?? this.manageInventory,
      height: height ?? this.height,
      length: length ?? this.length,
      width: width ?? this.width,
      weight: weight ?? this.weight,
      originCountry: originCountry ?? this.originCountry,
      midCode: midCode ?? this.midCode,
      material: material ?? this.material,
      metadata: metadata ?? this.metadata,
      options: options?.map((e) => e.duplicate()).toList(),
      prices: prices?.map((e) => e.duplicate()).toList(),
      //
      productId: null,
      product: null,
      purchasable: null,
      variantRank: null,
      inventoryItems: null,
      createdAt: null,
      updatedAt: null,
      deletedAt: null,
    );
  }
}
