name: medusa_api_client
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  retrofit: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  lints: ^5.0.0
  retrofit_generator: ^9.2.0
  test: ^1.24.0
