swagger_to_dart:
  # You can use a local file path
  input_directory: lib/medusa_api.json
  output_directory: lib/src/gen
  api_client_class_name: ApiClient
  imports:
    - import 'package:dio/dio.dart';
  skipped_parameters:
    - Accept-Language
    - X-Language
    - X-Platform

  model:
    support_generic_arguments: true

  api_client:
    use_class_for_query_parameters: true
  # Or you can use a URL to directly download the spec
  # url: https://example.com/api/swagger.json
